CROMOSP_LINES : "DataSet/Inputs/c_lines_spectrum.txt"
ATOMIC_LINES  : "DataSet/Inputs/atomic_lines.tsv"
SPECTRUM      : "DataSet/Inputs/Subtracted_spectrum.txt"
THEORIC_CROMOSP_LINES : "DataSet/Inputs/theoric_c_lines.txt" 